version: "3.8"

services:
  app:
    build: ./app
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - db
    env_file:
      - .env
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  static_volume:
  media_volume:
